import * as vscode from 'vscode';
import * as fs from 'fs';
import * as path from 'path';

export class ExportManager {
  async exportToMarkdown(explanation: any): Promise<void> {
    const timestamp = new Date().toLocaleString('en-IN');
    const language = explanation.language || 'unknown';

    const markdown = `# CodeSensei Explanation 🥋

**Language:** ${language}
**Date:** ${timestamp}
**Mode:** ${explanation.mode || 'english'}

---

## Code
\`\`\`${language}
${explanation.code || ''}
\`\`\`

---

## 🟢 Level 1: What is happening?
${explanation.level1}

## 🔵 Level 2: Why this design?
${explanation.level2}

## 🟠 Common Pitfalls
${explanation.pitfalls}

## 🔵 Socratic Question
${explanation.socraticQuestion}

${explanation.errorExplanation ? `## ⚠️ Error Explanation\n${explanation.errorExplanation}\n` : ''}

---
*Generated by CodeSensei — AI Reasoning Coach for Indian Developers* 🥋
`;

    const saveUri = await vscode.window.showSaveDialog({
      defaultUri: vscode.Uri.file(
        path.join(
          vscode.workspace.workspaceFolders?.[0]?.uri.fsPath || process.env.HOME || '',
          `codesensei-${Date.now()}.md`
        )
      ),
      filters: { 'Markdown': ['md'] }
    });

    if (saveUri) {
      fs.writeFileSync(saveUri.fsPath, markdown);
      const open = await vscode.window.showInformationMessage(
        '✅ Notes exported successfully!',
        'Open File'
      );
      if (open === 'Open File') {
        vscode.commands.executeCommand('vscode.open', saveUri);
      }
    }
  }
}
